# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Work In Progress
email: wip@plukevdh.me
description: > 
  Rambling thoughts from a work in progress.
  Trying to understand what can be known about God and seeking to discover
  what those things mean for my life. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wip.plukevdh.me" # the base hostname & protocol for your site
twitter_username: plukevdh

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"
paginate: 5

gems: [jekyll-paginate]
paginate_path: "/page/:num/"

